name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |

            APP_DIR="/var/www/avnerglobal"

            echo "Checking if app directory exists..."
            if [ ! -d "$APP_DIR/.git" ]; then
              echo "First time setup. Cloning repository..."
              mkdir -p $APP_DIR
              cd $APP_DIR
              git clone https://github.com/anaswebdevpro/Quantix-Global.git .
            else
              echo "Repository exists. Pulling latest code..."
              cd $APP_DIR
              git pull origin master
            fi

            echo "Installing dependencies..."
            npm install

            echo "Building project..."
            npm run build

            echo "Restarting PM2..."
            pm2 restart avnerglobal || pm2 start npm --name "avnerglobal" -- start

            echo "Deployment completed successfully!"
